version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: gather_tweet-admin
      POSTGRES_PASSWORD: gather_tweet-admin1234!
      POSTGRES_DB: gather-tweet
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      - TZ=Asia/Seoul

volumes:
  postgres:
